version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=43316
    expose:
      - '43316'
    ports:
      - '43316:43316'
  
  importer:
    build: .
    depends_on:
      - db
    environment:
      - DB_PORT=43316
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_TYPE=postgres
    